### ISSUE TITLE
Add a method to Io

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/commons#17]
```
def toLinesFromResource(path: String): Iterator[String] = {
  Source.fromInputStream(getClass.getResourceAsStream(path)).withClose(() => stream.close()).getLines
}	
```

**Comment by tfenne** [comment]
Why put this here and not just in a PR @nh13 ?

**Comment by nh13** [comment]
Needed five more minutes and didn't want to forget.  I now have five minutes (nope, gotta go), I'll make a PR.

**Comment by nh13** [comment]
https://github.com/fulcrumgenomics/commons/pull/19
